[package]
name = "jpp_core"
authors.workspace = true
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
serde_json = "1"
regex = "1"
smallvec = "1.11"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }

[lints]
workspace = true
