[package]
name = "jpp_cli"
authors.workspace = true
edition.workspace = true
version.workspace = true
publish.workspace = true

[[bin]]
name = "jpp"
path = "src/main.rs"

[dependencies]
jpp_core = { path = "../jpp_core" }
serde_json = "1"

[lints]
workspace = true
